blueprint:
  name: Sonoff M5 3-Gang Switch Controller
  description: |
    Control automations using the Sonoff M5 3-Gang smart switch.

    - Each gang supports ON, OFF, and TOGGLE triggers.
    - Works with Sonoff LAN HACS integration.
    - Assign individual actions to each gang and switch state.

  domain: automation
  author: Kamil Kara
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
          multiple: false
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch
          multiple: false
    switch_3:
      name: Switch 3
      selector:
        entity:
          domain: switch
          multiple: false

    ### Switch 1 Actions
    switch_1_on:
      name: Switch 1 - Turned ON
      default: []
      selector:
        action: {}

    switch_1_off:
      name: Switch 1 - Turned OFF
      default: []
      selector:
        action: {}

    switch_1_toggle:
      name: Switch 1 - Toggled
      default: []
      selector:
        action: {}

    ### Switch 2 Actions
    switch_2_on:
      name: Switch 2 - Turned ON
      default: []
      selector:
        action: {}

    switch_2_off:
      name: Switch 2 - Turned OFF
      default: []
      selector:
        action: {}

    switch_2_toggle:
      name: Switch 2 - Toggled
      default: []
      selector:
        action: {}

    ### Switch 3 Actions
    switch_3_on:
      name: Switch 3 - Turned ON
      default: []
      selector:
        action: {}

    switch_3_off:
      name: Switch 3 - Turned OFF
      default: []
      selector:
        action: {}

    switch_3_toggle:
      name: Switch 3 - Toggled
      default: []
      selector:
        action: {}

    automation_mode:
      name: Automation Mode
      default: queued
      selector:
        select:
          options:
            - single
            - queued
            - restart
            - parallel

mode: !input automation_mode

trigger:
  - platform: state
    entity_id: !input switch_1
  - platform: state
    entity_id: !input switch_2
  - platform: state
    entity_id: !input switch_3

action:
  - choose:
      # Switch 1
      - conditions:
          - condition: trigger
            id: switch_1
          - condition: state
            entity_id: !input switch_1
            state: "on"
        sequence: !input switch_1_on

      - conditions:
          - condition: trigger
            id: switch_1
          - condition: state
            entity_id: !input switch_1
            state: "off"
        sequence: !input switch_1_off

      - conditions:
          - condition: trigger
            id: switch_1
        sequence: !input switch_1_toggle

      # Switch 2
      - conditions:
          - condition: trigger
            id: switch_2
          - condition: state
            entity_id: !input switch_2
            state: "on"
        sequence: !input switch_2_on

      - conditions:
          - condition: trigger
            id: switch_2
          - condition: state
            entity_id: !input switch_2
            state: "off"
        sequence: !input switch_2_off

      - conditions:
          - condition: trigger
            id: switch_2
        sequence: !input switch_2_toggle

      # Switch 3
      - conditions:
          - condition: trigger
            id: switch_3
          - condition: state
            entity_id: !input switch_3
            state: "on"
        sequence: !input switch_3_on

      - conditions:
          - condition: trigger
            id: switch_3
          - condition: state
            entity_id: !input switch_3
            state: "off"
        sequence: !input switch_3_off

      - conditions:
          - condition: trigger
            id: switch_3
        sequence: !input switch_3_toggle