blueprint:
  name: Sonoff M5 3-Gang Button Controller
  description: |
    Control automations using the 3-gang Sonoff M5 touch switch.
    - Each gang (button) supports single, double, and hold press actions.
    - Requires the "Sonoff LAN" HACS integration in auto mode.
    [View button layout](https://example.com/image-of-3-gang-layout)
  domain: automation
  author: Kamil Kara
  input:
    sonoff_sensor:
      name: Sonoff M5 Sensor
      description: "Select the Sonoff M5 sensor entity"
      selector:
        entity:
          domain: sensor
          integration: sonoff

    ### ☝️ SINGLE PRESS ACTIONS
    single_press_header:
      name: "☝️ SINGLE PRESS ACTIONS"
      description: "Define actions for each gang single press."
      default: "Info only"
      selector:
        text: {}

    button_1_single:
      name: Button 1 - Single Press
      default: []
      selector:
        action: {}

    button_2_single:
      name: Button 2 - Single Press
      default: []
      selector:
        action: {}

    button_3_single:
      name: Button 3 - Single Press
      default: []
      selector:
        action: {}

    ### ✌️ DOUBLE PRESS ACTIONS
    double_press_header:
      name: "✌️ DOUBLE PRESS ACTIONS"
      description: "Define actions for each gang double press."
      default: "Info only"
      selector:
        text: {}

    button_1_double:
      name: Button 1 - Double Press
      default: []
      selector:
        action: {}

    button_2_double:
      name: Button 2 - Double Press
      default: []
      selector:
        action: {}

    button_3_double:
      name: Button 3 - Double Press
      default: []
      selector:
        action: {}

    ### ✋ HOLD PRESS ACTIONS
    hold_press_header:
      name: "✋ HOLD PRESS ACTIONS"
      description: "Define actions for each gang hold press."
      default: "Info only"
      selector:
        text: {}

    button_1_hold:
      name: Button 1 - Hold
      default: []
      selector:
        action: {}

    button_2_hold:
      name: Button 2 - Hold
      default: []
      selector:
        action: {}

    button_3_hold:
      name: Button 3 - Hold
      default: []
      selector:
        action: {}

    automation_mode:
      name: Automation Mode
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

mode: !input automation_mode

trigger:
  - platform: state
    entity_id: !input sonoff_sensor
    to:
      - "button_1_single"
      - "button_2_single"
      - "button_3_single"
      - "button_1_double"
      - "button_2_double"
      - "button_3_double"
      - "button_1_hold"
      - "button_2_hold"
      - "button_3_hold"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_1_single"
        sequence: !input button_1_single

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_2_single"
        sequence: !input button_2_single

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_3_single"
        sequence: !input button_3_single

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_1_double"
        sequence: !input button_1_double

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_2_double"
        sequence: !input button_2_double

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_3_double"
        sequence: !input button_3_double

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_1_hold"
        sequence: !input button_1_hold

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_2_hold"
        sequence: !input button_2_hold

      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_3_hold"
        sequence: !input button_3_hold