blueprint:
  name: Sonoff R5 Button Controller
  description: |
    Control multiple lights and switches using the Sonoff R5 buttons.
    - Each button has 3 actions: Single press, Double press, and Hold press.
    - Assign different devices or services to each action.
    - Each action can optionally have a custom automation mode.
  domain: automation
  input:
    sonoff_sensor:
      name: Sonoff R5 Sensor
      description: "Select the Sonoff R5 sensor entity"
      selector:
        entity:
          domain: sensor

    # Global Automation Mode (default for all actions unless overridden)
    global_automation_mode:
      name: Default Automation Mode
      description: "Select the default automation mode for all actions."
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    # --- Button 1 ---
    enable_mode_button_1_single:
      name: Enable Custom Mode for Button 1 Single Press
      default: false
      selector:
        boolean:
    
    mode_button_1_single:
      name: Mode for Button 1 Single Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_1_single:
      name: Button 1 - Single Press Action
      default: []
      selector:
        action: {}

    enable_mode_button_1_double:
      name: Enable Custom Mode for Button 1 Double Press
      default: false
      selector:
        boolean:

    mode_button_1_double:
      name: Mode for Button 1 Double Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_1_double:
      name: Button 1 - Double Press Action
      default: []
      selector:
        action: {}

    enable_mode_button_1_hold:
      name: Enable Custom Mode for Button 1 Hold Press
      default: false
      selector:
        boolean:

    mode_button_1_hold:
      name: Mode for Button 1 Hold Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_1_hold:
      name: Button 1 - Hold Press Action
      default: []
      selector:
        action: {}

    # --- Repeat for Buttons 2-6 ---
{% for button in range(2, 7) %}
    enable_mode_button_{{ button }}_single:
      name: Enable Custom Mode for Button {{ button }} Single Press
      default: false
      selector:
        boolean:

    mode_button_{{ button }}_single:
      name: Mode for Button {{ button }} Single Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_{{ button }}_single:
      name: Button {{ button }} - Single Press Action
      default: []
      selector:
        action: {}

    enable_mode_button_{{ button }}_double:
      name: Enable Custom Mode for Button {{ button }} Double Press
      default: false
      selector:
        boolean:

    mode_button_{{ button }}_double:
      name: Mode for Button {{ button }} Double Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_{{ button }}_double:
      name: Button {{ button }} - Double Press Action
      default: []
      selector:
        action: {}

    enable_mode_button_{{ button }}_hold:
      name: Enable Custom Mode for Button {{ button }} Hold Press
      default: false
      selector:
        boolean:

    mode_button_{{ button }}_hold:
      name: Mode for Button {{ button }} Hold Press
      default: queued
      selector:
        select:
          options:
            - "single"
            - "queued"
            - "restart"
            - "parallel"

    button_{{ button }}_hold:
      name: Button {{ button }} - Hold Press Action
      default: []
      selector:
        action: {}
{% endfor %}

  source_url: "https://github.com/kamilkara/HA_blueprints/blob/main/blueprints/automation/sonoff_r5/sonoff_r5.yaml"

mode: !input global_automation_mode  # Default mode unless overridden

trigger:
  - platform: state
    entity_id: !input sonoff_sensor
    to:
      - "button_1_single"
      - "button_1_double"
      - "button_1_hold"
      - "button_2_single"
      - "button_2_double"
      - "button_2_hold"
      - "button_3_single"
      - "button_3_double"
      - "button_3_hold"
      - "button_4_single"
      - "button_4_double"
      - "button_4_hold"
      - "button_5_single"
      - "button_5_double"
      - "button_5_hold"
      - "button_6_single"
      - "button_6_double"
      - "button_6_hold"

action:
  - choose:
{% for button in range(1, 7) %}
      # Button {{ button }} - Single Press
      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_{{ button }}_single"
        sequence:
          - if:
              - condition: template
                value_template: "{{ iinput.enable_mode_button_{{ button }}_single }}"
            then:
              - service: automation.turn_on
                data:
                  mode: !input mode_button_{{ button }}_single
            else:
              - service: automation.turn_on
                data:
                  mode: !input global_automation_mode
          - choose: !input button_{{ button }}_single

      # Button {{ button }} - Double Press
      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_{{ button }}_double"
        sequence:
          - if:
              - condition: template
                value_template: "{{ iinput.enable_mode_button_{{ button }}_double }}"
            then:
              - service: automation.turn_on
                data:
                  mode: !input mode_button_{{ button }}_double
            else:
              - service: automation.turn_on
                data:
                  mode: !input global_automation_mode
          - choose: !input button_{{ button }}_double

      # Button {{ button }} - Hold Press
      - conditions:
          - condition: state
            entity_id: !input sonoff_sensor
            state: "button_{{ button }}_hold"
        sequence:
          - if:
              - condition: template
                value_template: "{{ iinput.enable_mode_button_{{ button }}_hold }}"
            then:
              - service: automation.turn_on
                data:
                  mode: !input mode_button_{{ button }}_hold
            else:
              - service: automation.turn_on
                data:
                  mode: !input global_automation_mode
          - choose: !input button_{{ button }}_hold
{% endfor %}
